import type { Metadata } from 'next';
import { Poppins, Roboto, Roboto_Condensed } from 'next/font/google';
import './globals.css';

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'], display: 'swap', variable: '--font-roboto' });
const robotoCondensed = Roboto_Condensed({ subsets: ['latin'], display: 'swap', variable: '--font-roboto-condensed' });
const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'], display: 'swap', variable: '--font-poppins' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
